// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BasicCleanOptions “基础功能”区的全部开关选项（合并后）。
 * 
 * 历史上 BasicCleaner 9 条 + ExtraCleaner 17 条共 26 条规则分散在两个
 * struct 里、UI 上也是两个 SectionCard。经用户要求统一为单一「基础功能」
 * 分区后，本 struct 收纳所有字段；json tag 保持 "basicClean" 不变，
 * 以保证老版本持久化的 settings.json 仍可读取（缺的字段为零值）。
 * 
 * 设计要点：
 *   - 全部为 bool 开关，单条规则独立可勾选；
 *   - 字段名即 Go 端约定的开关常量，前端 binding 自动生成同名 TypeScript 字段；
 *   - 命名风格为 UpperCamelCase，对应前端 lowerCamelCase（binding 自动转换）；
 *   - 各规则的执行顺序由 cleanrules 包内部编排，此处不关心。
 */
export interface BasicCleanOptions {
    /**
     * ---- 字符（Character-level normalization） ----
     * 删除行首空白
     */
    "trimLeadingWhitespace": boolean;

    /**
     * 删除行尾空白
     */
    "trimTrailingWhitespace": boolean;

    /**
     * 删除 UTF-8 BOM
     */
    "removeUTF8BOM": boolean;

    /**
     * 删除零宽字符
     */
    "removeZeroWidthChars": boolean;

    /**
     * 全角字符转半角字符
     */
    "fullWidthToHalfWidth": boolean;

    /**
     * 康熙部首替换为正常字符
     */
    "replaceKangxiRadicals": boolean;

    /**
     * ---- 标点（Punctuation conversion） ----
     * 英文标点 → 中文标点
     */
    "punctEnglishToChinese": boolean;

    /**
     * 中文标点 → 英文标点
     */
    "punctChineseToEnglish": boolean;

    /**
     * ---- 引用角标（Citation marks） ----
     * 删除 (1)、(2,3)、(4-7)
     */
    "removeCiteParen": boolean;

    /**
     * 删除 [1]、【2,3】、[4-7]
     */
    "removeCiteBracket": boolean;

    /**
     * ---- 空白与换行（Whitespace / newlines） ----
     * 合并连续换行为单个（严格）
     */
    "collapseNewlines": boolean;

    /**
     * 所有换行 → 空格
     */
    "newlineToSpace": boolean;

    /**
     * 合并连续空格为单个
     */
    "collapseSpaces": boolean;

    /**
     * 删除完全空白的行
     */
    "removeEmptyLines": boolean;

    /**
     * 合并连续空行至最多 MaxBlankLines
     */
    "collapseBlankLines": boolean;

    /**
     * 上述合并后保留的最大连续空行数
     */
    "maxBlankLines": number;

    /**
     * ---- CJK / 数字 间距 ----
     * 删除 CJK 字符之间的空格
     */
    "removeSpaceBetweenCJK": boolean;

    /**
     * 在标点符号后添加空格
     */
    "spaceAfterPunctuation": boolean;

    /**
     * 删除小数点与数字之间的空格
     */
    "removeSpaceAtDecimal": boolean;

    /**
     * 在字母与数字之间添加空格
     */
    "spaceBetweenLetterAndDigit": boolean;

    /**
     * 删除冒号与数字之间的空格
     */
    "removeSpaceAtColon": boolean;

    /**
     * ---- 中文排版（参考 sspai.com/post/37815） ----
     * 规范中文排版
     */
    "normalizeChineseTypography": boolean;

    /**
     * ---- 简繁转换 ----
     * 简 → 繁
     */
    "simplifiedToTraditional": boolean;

    /**
     * 繁 → 简
     */
    "traditionalToSimplified": boolean;

    /**
     * ---- 输出换行符（仅在 Clean 时影响是否统一；最终 LF/CRLF/keep 由 processor.toEnding 决定） ----
     * 是否在 Clean 阶段先归一为 LF
     */
    "normalizeLineEndings": boolean;

    /**
     * 最终输出换行符（NormalizeLineEndings 为真时生效）
     */
    "lineEnding": LineEnding;
}

/**
 * FileEntry 表示一个已扫描到的文本文件。
 */
export interface FileEntry {
    /**
     * 文件的绝对路径
     */
    "path": string;

    /**
     * 文件名（含扩展名）
     */
    "name": string;

    /**
     * 文件大小（字节）
     */
    "size": number;

    /**
     * 扩展名（含点，如 .txt）
     */
    "ext": string;
}

/**
 * LineEnding 指定统一换行符的目标。
 */
export enum LineEnding {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 保持原文件换行符
     */
    LineEndingKeep = "keep",

    /**
     * 统一为 LF (\n)
     */
    LineEndingLF = "lf",

    /**
     * 统一为 CRLF (\r\n)
     */
    LineEndingCRLF = "crlf",
};

/**
 * ProcessOptions 一次文本处理的完整配置。
 * 
 * 注意：删除内容已合并进 Replace（Replace 为空即删除），不再单独成字段。
 * BasicClean 收纳所有“基础功能”开关（共 26 项），由 cleanrules.ApplyExtra 执行。
 */
export interface ProcessOptions {
    "basicClean": BasicCleanOptions;
    "replace": ReplaceRule[] | null;
}

/**
 * ProcessOutput 文本处理输出，供前端预览 / 批量处理使用。
 */
export interface ProcessOutput {
    /**
     * 处理后的文本
     */
    "text": string;

    /**
     * 处理统计
     */
    "result": ProcessResult;
}

/**
 * ProcessResult 单次 ProcessText 的统计信息。
 */
export interface ProcessResult {
    /**
     * 被删除的匹配数量
     */
    "deletedMatches": number;

    /**
     * 被替换的匹配数量
     */
    "replacedMatches": number;

    /**
     * 文本是否发生了变化
     */
    "changed": boolean;
}

/**
 * ReplaceRule 一条替换规则（普通文本或正则）。
 * 
 * “删除”只是“替换为空白内容”的特例：当 Replace 为空字符串时，
 * 该规则的效果即删除所有匹配到的 Find。因此删除与替换共用同一套规则，
 * 不再单独存在 Delete 字段。
 */
export interface ReplaceRule {
    "enabled": boolean;
    "find": string;
    "replace": string;
    "regex": boolean;
}
