// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 暴露给前端（Vue）的后端服务。
 * 
 * 设计原则：所有核心文本处理都由 Go 完成，前端只负责展示与交互，
 * 不重复实现任何文本处理逻辑。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as batch$0 from "./internal/batch/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scanner$0 from "./internal/scanner/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelBatch 取消正在进行的批量任务。
 */
export function CancelBatch(): $CancellablePromise<void> {
    return $Call.ByID(2119733904);
}

/**
 * ChooseDirectory 弹出系统“选择文件夹”对话框，返回所选目录（取消时返回空串）。
 */
export function ChooseDirectory(): $CancellablePromise<string> {
    return $Call.ByID(576708618);
}

/**
 * ChooseSavePath 弹出系统“保存文件”对话框，返回所选路径（取消时返回空串）。
 */
export function ChooseSavePath(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(3421218221, defaultName);
}

/**
 * ExportFiles 将多个处理结果写入用户选择的目标目录（多文件导出）。
 * 每个文件的 Path 为相对目标目录的路径，Data 为 base64 内容。
 * 返回成功写入的文件数量。
 */
export function ExportFiles(dir: string, files: $models.ExportFile[] | null): $CancellablePromise<number> {
    return $Call.ByID(4240397623, dir, files);
}

/**
 * GetSettings 读取持久化的偏好设置。
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(3018893939);
}

/**
 * OpenFolder 在系统文件管理器中打开指定目录（跨平台）。
 * 批量处理完成后，前端用它让用户一键跳转到输出目录。
 */
export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(840210810, path);
}

/**
 * ProcessBatch 批量处理文件。该方法立即返回，进度通过 "batch-progress" 事件推送，
 * 完成时通过 "batch-done" 事件推送汇总。可通过 CancelBatch 取消。
 */
export function ProcessBatch(opts: batch$0.Options): $CancellablePromise<void> {
    return $Call.ByID(2513707785, opts);
}

/**
 * ProcessText 文本处理核心入口。预览与批量处理共用此函数，确保逻辑一致。
 */
export function ProcessText(input: string, options: model$0.ProcessOptions): $CancellablePromise<model$0.ProcessOutput> {
    return $Call.ByID(2359560656, input, options);
}

/**
 * ReadTextFile 读取文本文件的原始字节并以字符串返回（按编码自动识别解码）。
 */
export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(3194043263, path);
}

/**
 * SaveFileBytes 将 base64 内容写入指定绝对路径（用于单文件 / ZIP 导出）。
 * 目标路径由系统“保存文件”对话框返回，用户已确认可覆盖。
 */
export function SaveFileBytes(path: string, dataBase64: string): $CancellablePromise<void> {
    return $Call.ByID(1661940096, path, dataBase64);
}

/**
 * SaveSettings 保存偏好设置。
 */
export function SaveSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(3784651466, s);
}

/**
 * ScanPaths 扫描给定的路径（可混合文件与文件夹），返回去重、排序后的文本文件列表。
 * 文件系统遍历统一在 Go 端完成，前端不重复实现。
 */
export function ScanPaths(paths: string[] | null, options: scanner$0.Options): $CancellablePromise<model$0.FileEntry[] | null> {
    return $Call.ByID(88425649, paths, options);
}

/**
 * Version 返回应用版本，用于前端展示（同时验证 Go ↔ Vue 调用链路）。
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1828333558);
}
