// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportFile 是桌面端原生导出的单个文件描述。
 * Path 为相对目标目录的路径（可包含子目录），Data 为 base64 编码的文件内容。
 */
export interface ExportFile {
    "path": string;
    "data": string;
}
