// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Options 扫描选项。
 */
export interface Options {
    /**
     * 是否递归扫描子文件夹
     */
    "includeSubfolders": boolean;

    /**
     * 允许的扩展名（.txt / txt / *.txt 均可）；为空表示不限类型
     */
    "extensions": string[] | null;

    /**
     * 最大文件数；<=0 表示使用内置硬上限
     */
    "maxFiles": number;
}
