// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Mode is the output strategy chosen by the user. String-typed so it
 * can be persisted (settings.json) and bound to TypeScript without a
 * separate enum mapping.
 */
export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ModeCreateSibling: 默认。安全、不覆盖原文件：
     * - 输入为文件夹 → 在其同级创建 `<basename>_TCoutput`
     * - 输入为单文件 → 在其父目录下创建 `<stem>_TCoutput`，文件落入该文件夹
     * 冲突时自动加 " (1)" / " (2)" 直至找到空名。
     */
    ModeCreateSibling = "create_sibling",

    /**
     * ModeCustom: 用户指定一个根输出目录：
     * - 文件夹输入 → `<root>/<basename>/<内部目录结构>`
     * - 文件输入   → `<root>/<basename>`（顶层冲突自动加 " (1)"）
     * 若 root 位于某个输入内部、被某个输入占用或为某个输入，BuildPlan 拒绝并报错。
     */
    ModeCustom = "custom",
};

/**
 * Options is the user-facing output configuration passed by the
 * frontend / persisted across sessions.
 * 
 * 跨语言 binding：JSON tag 即前端字段名（Wails 自动生成同名 TS 字段）。
 */
export interface Options {
    "mode": Mode;

    /**
     * CustomPath is the user-picked root output directory, only used
     * when Mode == ModeCustom. Ignored for ModeCreateSibling.
     */
    "customPath": string;
}
