// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as output$0 from "../output/models.js";

/**
 * Options 批量处理选项。
 * 
 * 输出配置由 internal/output.BuildPlan 统一处理（create_sibling /
 * custom 两种模式），原覆盖模式已下线。
 */
export interface Options {
    "paths": string[] | null;
    "process": model$0.ProcessOptions;
    "output": output$0.Options;
    "outputEncoding": string;
    "maxConcurrency": number;
}
