// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Settings 需要持久化的用户偏好。
 * 
 * 重要：只保存“勾选类”的通用选项（如基础清理开关、默认包含子文件夹、
 * 并发数、主题、语言）。用户每次输入的具体删除 / 替换文本规则不在此保存。
 */
export interface Settings {
    "basicClean": model$0.BasicCleanOptions;
    "defaultIncludeSubfolders": boolean;
    "maxConcurrency": number;

    /**
     * light | dark | system
     */
    "theme": string;

    /**
     * auto | zh | en
     */
    "language": string;
}
